### PR TITLE
Fixed a bug

### PR DESCRIPTION
**Pull request by pawelk1337**
This made get_revanced_tools function work again.
for some reason, I think GitHub changed the code for releases  and this stopped working I added the JSON which will be supported longer I think

Thanks 
 - ash

### CODE REVIEW

**Comment by AshKetchumPL** [comment]
I will make new pulls because why not?

**Comment by lorenzo3421** [comment]
Heya, Thank you very much for helping me out! I really appreciate it

I'll be checking the code soon

**Comment by pawelk1337** [comment]
Thanks for the quick response added more commits sorry for the double name i clicked up arrow too many times

**Comment by lorenzo3421** [comment]
For the already installed tool, what if they need an update?

**Comment by pawelk1337** [comment]
you can delete the commit but I could add some checks for the version like a JSON file or the version in the filename I'll try to make it if you want

**Comment by lorenzo3421** [comment]
You can try if you'd like to, I'd put the version on the filename to then be able to download a newer version and also remove the older one

**Comment by lorenzo3421** [comment]
> Thanks for the quick response added more commits sorry for the double name i clicked up arrow too many times

Also don't worry, it's completely fine 👍

**Comment by pawelk1337** [comment]
I'm gonna head to sleep now I'm gonna finish it tomorrow

**Comment by pawelk1337** [comment]
Ok it all was added (if the tool isn't the newest it downloads a new version)

**Pull request merged**
